[book]
authors = ["Olaperi Okuboyejo", "Lola Odelola", "Rob Cobb"]
language = "en"
multilingual = false
src = "src"
title = "Web Development Fundamentals"

[build]
build-dir = "output"
create-missing = false
use-default-preprocessors = false
